version: '3.8'

services:
  # PostgreSQL
  postgres_db:
    container_name: postgres-server
    restart: always
    image: postgres:alpine3.18
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
